# Generated by Django 2.2.10 on 2020-03-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_entry_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
