from django.db import models
from django.contrib.auth.models import User


class Entry(models.Model):
    # mandatory fields
    slug = models.SlugField(primary_key=True)
    title = models.TextField(max_length=60)
    description = models.TextField(max_length=200)
    markdown = models.TextField()

    # optional fields
    authors = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to="images", null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    # autogenerated fields
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
